name: Kotlin utils CI

on: [ push ]

jobs:
  run-tests:
    name: Run unit tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Run tests
        run: gradle test

  publish:
    name: Publish package
    if: github.ref == 'refs/heads/master'
    needs:
      - run-tests

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 8
      - name: Publish package
        run: gradle publish
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}